### ISSUE TITLE
Modules installed () 

### ISSUE THREAD

**Issue by Emilio-pra** [asahidari/differential_growth_snlite_b3d#1]
I need Help. I wanted to install this add on, but it just wont show up in my available Add on list. I aleady tried to drag it manually inot the add ons folder in scripts. I use an m1 Mac Book pro and blender 3.6

**Comment by asahidari** [comment]
Thank you for trying to use my script. But unfortunately, this script itself is not an add-on for Blender. This script is intended to be used in Sverchok add-on.

Sverchok add-on is a node-based add-on for Blender, and it contains a node to load custom script. If you try to use my script, you have to install Sverchok add-on in advance, and use the 'ScriptNodeLite' to load my script.

The way to use my script in Sverchok is written in my project's README.md, so please read it at first.

**Comment by Emilio-pra** [comment]
Im sorry for my fast issue report. Yo are absolutely right. I figured the out 2h later ^^. 

But im having still Problems with the Sverchok Add On on Blender. Every time I restart blender the sverchok Module is not enabled. An the button does not function. So I have to install it again. Is there a solution for this. 

Thank you so much for your help and even more for your great work in the blender Community. 

Best Regards 

Milo

**Comment by Emilio-pra** [comment]
And could I be so cheeky and ask you another Question : 

I tried the grow on Mesh Tutorial task you got on the Github site. But my Mesh just grows inside of the mesh. And it doesn’t apply the Size. 

Im using apple silicon M1 MacBook Pro and Blender 3.5.1

￼


Im very thankful for your help 

Best regards 

Milo

**Comment by Emilio-pra** [comment]
Ok I Fexe the issue on a sphere by applying the scale. But it won’t function on a human made face. The mesh has no holes

**Comment by asahidari** [comment]
> Ok I Fexe the issue on a sphere by applying the scale. But it won’t function on a human made face. The mesh has no holes

It is nice to be fixed by applying the scale, and changing the size or the length of your mesh may be one of good solutions. If you do not have better results by modifying your mesh, you probably have to change some parameters in this script.

This script has many parameters, so it might be difficult to get satisfactory results at first. I also struggled to have good shape for the first time. I hope you will get better shapes through trial and error.

By the way, one expert has already made mesh growth 'add-on' for Blender.
https://github.com/inca/blender-differential-growth
If you do not yet have tried this, and If you find my script too complicated or difficult to use, this add-on maybe worth trying.

Best regards.

**Comment by Emilio-pra** [comment]
Tahnk you so Much for your help. But the add on by Inca isn’t fulfilling my ambition like your team :))) One more Questions I fixed everything on the Line Growth but now Im having Bugs with the Growth Mesh. There are unwanted extreme Line One the mesh. Do you know the solution for this one. 

And Do you also have an Idea How I could change the Colors while Growth. And give it a more complex look 
￼

**Comment by asahidari** [comment]
> But the add on by Inca isn’t fulfilling my ambition like your team

I hope my script could fulfill your needs :).

> There are unwanted extreme Line One the mesh. Do you know the solution for this one.

Hmm, my answer might not work well in your case, but if I were you, I would try to:
* make the lengths of all edges in the original mesh nearly equal as much as possible (, which means you should avoid to contain extremely irregular length-edges).
* change the size of your mesh gradually to find the size that the extreme line would disappear.
* change the parameters in the script, such as MAX_VELOCITY, SEPARATION(COHESION)_DISTANCE(FORCE).

> Do you also have an Idea How I could change the Colors while Growth. And give it a more complex look

I cannot say for sure. But using 'vertex color' might be a hope. If you can change vertex colors according to the distance from a certain point(, and if the rendered result would work fine), you would have a result you want.

**Comment by asahidari** [comment]
The original purpose of this issue was already solved. Though I have been worried if my last comment was not useful, I could not have any comment over a month. I quit worrying about it and I close this issue. Bye for now!
